name: Docker Image CI

on:
  push:
    branches: [ "iscfer" ]
  pull_request:
    branches: [ "iscfer" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
      run: |
        echo "Iniciando logi docker hub"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWD
        echo "Fin del login docker hub"
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
