name: Docker Image CI

on:
  push:
    branches: [ "iscfer" ]
  pull_request:
    branches: [ "iscfer" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWD
        
    - name: Build the Docker image
      run: docker build -t iscfer933/test-docker-graphql:0.0.2 .

    - name: Push Docker image
      run: docker push iscfer933/test-docker-graphql:0.0.2 .
