name: Docker Image CI

on:
  push:
    branches: [ "iscfer" ]
  pull_request:
    branches: [ "iscfer" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.0.1
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
      
    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWD
        
    - name: Build the Docker image
      env: 
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t iscfer933/test-docker-graphql:$NEW_VERSION .
        docker build -t iscfer933/test-docker-graphql:latest .

    - name: Push Docker image
      env:
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker push iscfer933/test-docker-graphql:$NEW_VERSION
        docker push iscfer933/test-docker-graphql:latest
